name: CI

on:
  push:
    branches:
      - 'dev*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install dependencies
        run: go get -v ./...

      - name: Run tests
        run: go test -v ./...
